# Generated by Django 3.1.3 on 2020-11-05 11:21

from django.db import migrations, models
import django.db.models.deletion
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=40)),
                ('seed', models.IntegerField(default=quizzes.models._randint)),
                ('state', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='IN_PROGRESS', max_length=255)),
                ('active_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.CreateModel(
            name='QuizQuestionResponseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.answer')),
                ('quiz_question_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.quizquestionresponse')),
            ],
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='answers',
            field=models.ManyToManyField(through='quizzes.QuizQuestionResponseAnswer', to='quizzes.Answer'),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='quiz_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AddConstraint(
            model_name='quizquestionresponseanswer',
            constraint=models.UniqueConstraint(fields=('quiz_question_response', 'answer'), name='unique_answer'),
        ),
    ]
