# Generated by Django 3.1.3 on 2020-11-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
